name: "OpenWrt SDK"
description: "Build OpenWrt packages via the SDK"
author: aparcar
runs:
  using: 'composite'
  steps:
    - run: sudo chown -R 1000:1000 $GITHUB_WORKSPACE
      shell: bash
    - run: docker build --build-arg CONTAINER --build-arg ARCH -t sdk $GITHUB_ACTION_PATH
      shell: bash
    - run: |
        docker run --rm \
          --env BUILD_LOG \
          --env EXTRA_FEEDS \
          --env FEEDNAME \
          --env GITHUB_WORKSPACE \
          --env IGNORE_ERRORS \
          --env KEY_BUILD \
          --env NO_DEFAULT_FEEDS \
          --env NO_REFRESH_CHECK \
          --env NO_SHFMT_CHECK \
          --env PACKAGES \
          --env V \
          --workdir /github/workspace \
          -v $(pwd):/github/workspace \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          sdk
      shell: bash
    - run: sudo chown -R --reference=$GITHUB_WORKSPACE/.. $GITHUB_WORKSPACE
      shell: bash
