name: "OpenWrt SDK"
description: "Build OpenWrt packages via the SDK"
author: aparcar
runs:
  using: 'composite'
  steps:
    - run: |
        echo "::set-output name=artifacts_dir::${ARTIFACTS_DIR:-$GITHUB_WORKSPACE}"
        echo "::set-output name=feed_dir::${FEED_DIR:-$GITHUB_WORKSPACE}"
      shell: bash
      id: inputs
    - run: sudo chown -R 1000:1000 ${{ steps.inputs.outputs.artifacts_dir }} ${{ steps.inputs.outputs.feed_dir }}
      shell: bash
    - run: docker build --build-arg CONTAINER --build-arg ARCH -t sdk $GITHUB_ACTION_PATH
      shell: bash
    - run: |
        docker run --rm \
          --env BUILD_LOG \
          --env EXTRA_FEEDS \
          --env FEEDNAME \
          --env IGNORE_ERRORS \
          --env KEY_BUILD \
          --env NO_DEFAULT_FEEDS \
          --env NO_REFRESH_CHECK \
          --env NO_SHFMT_CHECK \
          --env PACKAGES \
          --env V \
          -v ${{ steps.inputs.outputs.artifacts_dir }}:/artifacts \
          -v ${{ steps.inputs.outputs.feed_dir }}:/feed \
          sdk
      shell: bash
    - run: sudo chown -R --reference=${{ steps.inputs.outputs.artifacts_dir }}/.. ${{ steps.inputs.outputs.artifacts_dir }}
      shell: bash
    - run: sudo chown -R --reference=${{ steps.inputs.outputs.feed_dir }}/.. ${{ steps.inputs.outputs.feed_dir }}
      shell: bash
